### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by adalpari** [Krupen/AutoplayVideos#36]
I'm getting an internal NPE related with the uri when the source is set.
I am sure that the uri is not null before set the video uri `setVideoUrl(uri.toString());`

Could be the issue related with recycled view?

Thank you so much

_Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:989)
       at android.media.MediaPlayer.setDataSource(MediaPlayer.java:972)
       at com.allattentionhere.autoplayvideos.AAH_CustomVideoView.onSurfaceTextureAvailable(S:224)
       at android.view.TextureView.getHardwareLayer(TextureView.java:368)
       at android.view.View.updateDisplayListIfDirty(View.java:15219)
       at android.view.View.draw(View.java:16015)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
       at android.view.View.updateDisplayListIfDirty(View.java:15237)
       at android.view.View.draw(View.java:16015)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
       at android.view.View.draw(View.java:16248)
       at android.view.View.updateDisplayListIfDirty(View.java:15242)
       at android.view.View.draw(View.java:16015)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
       at android.view.View.draw(View.java:16248)
       at android.view.View.updateDisplayListIfDirty(View.java:15242)
       at android.view.View.draw(View.java:16015)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
       at android.view.View.updateDisplayListIfDirty(View.java:15237)
       at android.view.View.draw(View.java:16015)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3765)
       at android.support.v7.widget.RecyclerView.drawChild(S:4581)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3555)
       at android.view.View.draw(View.java:16248)
       at android.support.v7.widget.RecyclerView.draw(S:3987)
       at android.view.View.updateDisplayListIfDirty(View.java:15242)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
       at android.view.View.updateDisplayListIfDirty(View.java:15202)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2662)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2481)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2091)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1127)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6156)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:892)
       at android.view.Choreographer.doCallbacks(Choreographer.java:704)
       at android.view.Choreographer.doFrame(Choreographer.java:640)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:878)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)_

**Comment by Krupen** [comment]
I need to see the code to be able to track the problem. One of the things which can cause this is not giving permission to write in external storage on above Marshmallow. If so, go to settings -> apps -> your app and give all permissions.

**Comment by adalpari** [comment]
The error is not reproducible. I'm getting it from Crashlytics, so I'm not sure about the real state. Meanwhile I'm going to check the permission you tell me.

This is the code I have in the card inside the list. Pretty simple.

    public abstract class AutoPlayerCard extends AAH_CustomViewHolder {

    @BindView(R.id.card_image)
    SimpleDraweeView image;

    @BindView(R.id.img_playback)
    ImageView imgPlayback;

    @BindView(R.id.img_vol)
    ImageView imgVol;

    @BindView(R.id.card_title)
    TextView title;

    private boolean isMuted = true;

    AutoPlayerCard(View view) {
        super(view);
    }

    @Override
    public void refreshHolder(Content content, int width) {
        super.refreshHolder(content, context, width);

        resetState();
        setTitle();

        setMedia(content, width);
    }

    private void resetState() {
        isMuted = true;
    }

    private void setTitle() {
        String titleText = DateUtil.getLocallyFormattedDateString(content.getTimestamp());
        AndroidUtil.setText(title, titleText);
    }

    private void setMedia(Content content, int width) {
        final Uri uri = UriHelper.from(content);
        FrescoHelper.loadOptimized(image, uri, width, null);

        if (uri != null) {
            setVideoUrl(uri.toString());
        }
    }

    @Override
    public void showThumb() {
        image.setVisibility(View.VISIBLE);
    }

    @Override
    public void videoStarted() {
        image.setVisibility(View.GONE);

        imgPlayback.setImageResource(R.drawable.ic_pause);
        handleMuteUnmute();
    }

    private void handleMuteUnmute() {
        if (isMuted) {
            muteVideo();
            imgVol.setImageResource(R.drawable.ic_mute);
        } else {
            unmuteVideo();
            imgVol.setImageResource(R.drawable.ic_unmute);
        }
    }

    @Override
    public void pauseVideo() {
        super.pauseVideo();
        imgPlayback.setImageResource(R.drawable.ic_play);
    }

    @OnClick({R.id.img_vol, R.id.card_video})
    public void onClickVol(View view) {
        isMuted = !isMuted;
        handleMuteUnmute();
    }

    @OnClick(R.id.img_playback)
    public void onClickPlay(View view) {
        try {
            if (isPlaying()) {
                pauseVideo();
                setPaused(true);
            } else {
                if (!Util.isNullOrBlank(getVideoUrl())) {
                    playVideo();
                    setPaused(false);
                }
            }
        } catch (Throwable ex) {
            CriticalLogger.error("Error in onClickPlay", ex);
        }
    }

Thank you so much

**Comment by Krupen** [comment]
Try setting videoUrl to empty String when URI is null.

**Comment by Yrlec** [comment]
Here are the details of the issue. http://crashes.to/s/dfccce3cf1d

**Comment by Krupen** [comment]
I looked into the code but not able to figure out what is causing it. If you could tell me steps to reproduce it, I might be able to track the bug and fix it.

**Comment by adalpari** [comment]
We still don't know how to reproduce it. But we are wondering if the cause could be: 

- Trying to load source after activity is stopped. As you see in the sent code, we are using your library when we refresh the holder. And also `onSurfaceTextureAvailable` is called when the view is available. But, have you noticed any issues related with lifecycle?

- Using an empty/bad url: before create the card, we are checking that mediaPlayer can load the video with the same uri. But anyway, being sure to set the source with a non-null and non-empty url (string) should be enough to prevent related crashes in your library? Are there any possibility to pass directly the uri to your library instead of the url? we are loading local videos too.

**Comment by adalpari** [comment]
I also have found an issue with Closeable object. It seems that the object is never released. Do you think that we missing anything about the cycle?

```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'release' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at android.view.Surface.setNativeObjectLocked(Surface.java:459)
                                                                   at android.view.Surface.<init>(Surface.java:145)
                                                                   at com.allattentionhere.autoplayvideos.AAH_CustomVideoView.startVideo(AAH_CustomVideoView.java:74)
                                                                   at com.allattentionhere.autoplayvideos.AAH_CustomViewHolder.playVideo(AAH_CustomViewHolder.java:32)
                                                                   at com.allattentionhere.autoplayvideos.AAH_CustomRecyclerView$3.run(AAH_CustomRecyclerView.java:158)
```

**Comment by Krupen** [comment]
Hi,
For playing local videos, you can check my answer in this issue: https://github.com/Krupen/AutoplayVideos/issues/23

About Closable Objects, I know of 2 of them (MediaPlayer and FileOutPutStream) which seem to be closed as per code. I will be looking to find more such objects and making sure these 2 gets closed properly every time. So far I think these 2 are closed properly.

**Comment by Krupen** [comment]
Hello @adalpari ,

I just release an update to the library and hopefully it fixes the crash.
In this fix, I have changed MediaPlayer context to Activity's context and added a null check for Activity and DataSource before calling any function on MediaPlayer.
Also there are some performance improvements.

Please update and let me know if fixes the issue. 
Also if possible, call `holder.setVideoUrl(<source>+"")` with an added empty string along with variable so that DataSource is never null.

**Comment by Krupen** [comment]
@adalpari @Yrlec  I hope all the issues are resolved. If not, feel free to reopen this issue.
