### ISSUE TITLE
Blank view

### ISSUE THREAD

**Issue by jeremy-jamez** [Krupen/AutoplayVideos#37]
This is in reference to a previous issue where I was using FirebaseRecyclerAdapter #33 . However, I've now created my own adapter and have successfully retrieved the database info into an ArrayList. The issue now is that the AAH_CustomRecyclerView is not being displayed, which therefore means the ViewHolder methods are not being called.
In the design view for recyclerview my activity, this error is being displayed:
```
The following classes could not be instantiated:
- com.allattentionhere.autoplayvideos.AAH_CustomRecyclerView (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  
If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.NullPointerException   at
android.os.storage.StorageManager.getVolumeList(StorageManager.java:922)   at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:87)   at android.os.Environment.getExternalStorageDirectory(Environment.java:404)   at com.allattentionhere.autoplayvideos.AAH_CustomRecyclerView.<init>(AAH_CustomRecyclerView.java:41)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard  
``` 
And the view is being displayed as a grey box in the preview. When the app is run, nothing is displayed in that particular activity. 

Here's the code for my adapter and firebase database query:
**MultiViewTypeAdapter:**
```
public class MultiViewTypeAdapter extends AAH_VideosAdapter {

    List<Map<String, Object>> postsList;
    Context mContext;

    public static class VideoTypeViewHolder extends AAH_CustomViewHolder{

        final ImageView img_vol,img_playback;
        boolean isMuted;

        public VideoTypeViewHolder(View itemView) {
            super(itemView);

            img_vol = (ImageView) itemView.findViewById(R.id.img_vol);
            img_playback = (ImageView) itemView.findViewById(R.id.img_playback);
        }

        @Override
        public void videoStarted() {
            super.videoStarted();
            img_playback.setImageResource(R.drawable.ic_pause);
            if (isMuted) {
                muteVideo();
                img_vol.setImageResource(R.drawable.ic_mute);
            } else {
                unmuteVideo();
                img_vol.setImageResource(R.drawable.ic_unmute);
            }
        }
        @Override
        public void pauseVideo() {
            super.pauseVideo();
            img_playback.setImageResource(R.drawable.ic_play_circle);
        }
    }

    public MultiViewTypeAdapter(List<Map<String, Object>> data, Context context){
        this.postsList = data;
        this.mContext = context;
    }

    @Override
    public AAH_CustomViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.video_feed_item, parent, false);
        return new VideoTypeViewHolder(view);
    }

    @Override
    public void onBindViewHolder(AAH_CustomViewHolder holder, int position) {
        holder.setImageUrl(postsList.get(position).post_img);
        holder.setVideoUrl(postsList.get(position).post_video);

        if(postsList.get(position).post_img != null && !postsList.get(position).post_img.isEmpty()){
            GlideApp.with(mContext)
                    .load(holder.getImageUrl())
                    .into(holder.getAAH_ImageView());
        }

        holder.setLooping(true);

        ((VideoTypeViewHolder)holder).img_playback.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (holder.isPlaying()) {
                    holder.pauseVideo();
                    holder.setPaused(true);
                } else {
                    holder.playVideo();
                    holder.setPaused(false);
                }
            }
        });

        ((VideoTypeViewHolder) holder).img_vol.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (((VideoTypeViewHolder) holder).isMuted) {
                    holder.unmuteVideo();
                    ((VideoTypeViewHolder) holder).img_vol.setImageResource(R.drawable.ic_unmute);
                } else {
                    holder.muteVideo();
                    ((VideoTypeViewHolder) holder).img_vol.setImageResource(R.drawable.ic_mute);
                }
                ((VideoTypeViewHolder) holder).isMuted = !((VideoTypeViewHolder) holder).isMuted;
            }
        });

        if (postsList.get(position).post_img == null) {
            ((VideoTypeViewHolder) holder).img_vol.setVisibility(View.GONE);
            ((VideoTypeViewHolder) holder).img_playback.setVisibility(View.GONE);
        } else {
            ((VideoTypeViewHolder) holder).img_vol.setVisibility(View.VISIBLE);
            ((VideoTypeViewHolder) holder).img_playback.setVisibility(View.VISIBLE);
        }

    }

    @Override
    public int getItemCount() {
        return postsList.size();
    }
}
```

**Firebase Database Query**
```
postsQuery.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {

                Posts posts = dataSnapshot.getValue(Posts.class);
                postsList.add(posts.toMap());

                multiViewTypeAdapter = new MultiViewTypeAdapter(postsList, FeedListActivity.this);
                multiViewTypeAdapter.notifyItemInserted(postsList.size());

            }

            @Override
            public void onChildChanged(DataSnapshot dataSnapshot, String s) {
                multiViewTypeAdapter.notifyDataSetChanged();
            }

            @Override
            public void onChildRemoved(DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                throw databaseError.toException();
            }
        });


        recyclerView.setActivity(FeedListActivity.this);
        recyclerView.setCheckForMp4(false);

        recyclerView.setAdapter(multiViewTypeAdapter);
```

**Comment by Krupen** [comment]
I think you forgot to do first fetch of the data, or you din't include in the code snippet above. You should be calling `addListenerForSingleValueEvent()` firebase function initially and then set the listener.

`addChildEventListener()` is only called when there is any insert/delete/update operation on the data.

**Comment by Krupen** [comment]
Also check if you have Storage permissions if you are trying it on device running Marshmallow or above.

**Comment by jeremy-jamez** [comment]
I've updated it to `addListenerForSingleValueEvent()` but it's still not being displayed. Log says `RecyclerView: No adapter attached.`
```
postsQuery.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {

                for(DataSnapshot snapshot : dataSnapshot.getChildren()){
                    Posts posts = snapshot.getValue(Posts.class);

                    postsList.add(posts.toMap());

                    multiViewTypeAdapter = new MultiViewTypeAdapter(postsList, FeedListActivity.this);
                    multiViewTypeAdapter.notifyItemInserted(postsList.size());

                    System.out.println("multiViewTypeAdapter: " + postsList);
                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });

        recyclerView.setActivity(FeedListActivity.this);
        recyclerView.setCheckForMp4(false);
        recyclerView.setLayoutManager(mLayoutManager);

        recyclerView.setAdapter(multiViewTypeAdapter);
```

When I log the results of `List<Map<String, Object>>` in the `MultiViewTypeAdapter` method, the child nodes are being logged as expected.
```
public MultiViewTypeAdapter(List<Map<String, Object>> data, Context context){
        this.postsList = data;
        this.mContext = context;

        System.out.println("multiViewTypeAdapter2344: " + postsList);
    }
```

And yes Storage permissions are granted.

**Comment by jeremy-jamez** [comment]
Also if it's any help, I'm using version 26.0.1 of the support library. I'm not able to test an earlier version because I get an error about manifest mismatch or something of the sort.

**Comment by Krupen** [comment]
For forcing to use previous library version, you can do as follows:
```
compile("com.android.support:appcompat-v7:23.0.1"){
    force = true
}
```

**Comment by Krupen** [comment]
About adapter, you need to set adapter after Firebase has finished fetching the data:
```
postsQuery.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {

                for(DataSnapshot snapshot : dataSnapshot.getChildren()){
                    Posts posts = snapshot.getValue(Posts.class);

                    postsList.add(posts.toMap());

                    multiViewTypeAdapter = new MultiViewTypeAdapter(postsList, FeedListActivity.this);
              
                    recyclerView.setActivity(FeedListActivity.this);
                    recyclerView.setCheckForMp4(false);
                    recyclerView.setLayoutManager(mLayoutManager);
                    recyclerView.setAdapter(multiViewTypeAdapter);

                    System.out.println("multiViewTypeAdapter: " + postsList);
                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });

       
```

**Comment by jeremy-jamez** [comment]
Okay, you were right, I've got the recyclerview to be displayed now but the videos and images are not being loaded.

**onBindViewHolder:**
```
@Override
    public void onBindViewHolder(final AAH_CustomViewHolder holder, int position) {

        holder.setImageUrl(postsList.get(position).get("post_img").toString());
        holder.setVideoUrl(postsList.get(position).get("post_video").toString());

        if(postsList.get(position).get("post_img").toString() != null && !postsList.get(position).get("post_img").toString().isEmpty()){
            GlideApp.with(mContext)
                    .load(holder.getImageUrl())
                    .into(holder.getAAH_ImageView());
        }

        holder.setLooping(true);

        ((VideoTypeViewHolder)holder).img_playback.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (holder.isPlaying()) {
                    holder.pauseVideo();
                    holder.setPaused(true);
                } else {
                    holder.playVideo();
                    holder.setPaused(false);
                }
            }
        });

        ((VideoTypeViewHolder) holder).img_vol.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (((VideoTypeViewHolder) holder).isMuted) {
                    holder.unmuteVideo();
                    ((VideoTypeViewHolder) holder).img_vol.setImageResource(R.drawable.ic_unmute);
                } else {
                    holder.muteVideo();
                    ((VideoTypeViewHolder) holder).img_vol.setImageResource(R.drawable.ic_mute);
                }
                ((VideoTypeViewHolder) holder).isMuted = !((VideoTypeViewHolder) holder).isMuted;
            }
        });

        if (postsList.get(position).get("post_video").toString() == null) {
            ((VideoTypeViewHolder) holder).img_vol.setVisibility(View.GONE);
            ((VideoTypeViewHolder) holder).img_playback.setVisibility(View.GONE);
        } else {
            ((VideoTypeViewHolder) holder).img_vol.setVisibility(View.VISIBLE);
            ((VideoTypeViewHolder) holder).img_playback.setVisibility(View.VISIBLE);
        }

    }
```

In the database, `post_video` is null for the ones that are images and `post_img` is null for the ones that are videos. Would this be the cause?

**Comment by Krupen** [comment]
It could be, but I would suggest you to go through Firebase documentation first before you use any library along with it. The issues you have raised are essentially in your implementation and nothing related to this library's code. 
Please feel free to re-open the issue if there is any bug related to the code of this library.
