### ISSUE TITLE
Null pointer Exception on scroll recyclerview.

### ISSUE THREAD

**Issue by trey-rosius** [Krupen/AutoplayVideos#42]
Hi, thanks for the amazing library, i have a multiple view type recyclerview, and i get a null pointer exception on scrolling. Here is the logcat printout

`FATAL EXCEPTION: main
                                                                 Process: com.rosius.tori, PID: 28476
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'com.allattentionhere.autoplayvideos.AAH_CustomVideoView com.allattentionhere.autoplayvideos.AAH_VideoImage.getCustomVideoView()' on a null object reference
                                                                     at com.allattentionhere.autoplayvideos.AAH_VideosAdapter.onViewDetachedFromWindow(AAH_VideosAdapter.java:26)
                                                                     at com.allattentionhere.autoplayvideos.AAH_VideosAdapter.onViewDetachedFromWindow(AAH_VideosAdapter.java:9)
                                                                     at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6947)
                                                                     at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:762)
                                                                     at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
                                                                     at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8041)
                                                                     at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8313)
                                                                     at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1368)
                                                                     at android.support.v7.widget.LinearLayoutManager.recycleViewsFromStart(LinearLayoutManager.java:1414)
                                                                     at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1483)
                                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1542)
                                                                     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1330)
                                                                     at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1074)
                                                                     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4838)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by Krupen** [comment]
Hi,
Are you using latest version of the library? ie. 0.1.8

**Comment by trey-rosius** [comment]
Yes Sir,
  compile 'com.allattentionhere:autoplayvideos:0.1.8'
And i also noticed, the content of my headerview isn't available anymore

**Comment by Krupen** [comment]
Found the issue, resolved it and released it. Update to version 0.1.9.
I have also updated the sample app with multiple view types.

**Comment by trey-rosius** [comment]
Thanks soo much.Tested it and it works fine. But now, content in my headerview only becomes vissible when i scroll about 5 items down the recyclerview. This doesn't occur when using the support recyclerview.
Do you have any idea what can be the issue?

**Comment by trey-rosius** [comment]
please close this issue. Everything works fine. thanks a lot for your assistance
